apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
  label:
    app:flask
spec:
  containers:
  - name: flask
    image: mingchak/flaskapp:latest
    ports:
      - containerPort: 5000
  imagePullSecrets:
  - name: myregistrykey
